''' A Collection of Methods for Data Collection & Processing '''
__author__ = 'rcj1492'
__created__ = '2015.11'
__module__ = 'labpack'
__version__ = '0.20'
__license__ = 'MIT'
__team__ = 'Collective Acuity'
__email__ = 'support@collectiveacuity.com'
__url__ = 'https://github.com/collectiveacuity/labPack'